title: Website
author: Dominic Stapf
email: dominic.stapf@gmail.com
description: Webdev, first GitHub website
theme: minima


twitter_username: HeadshotAMK
github_username:  Dominic-St


show_excerpts: false # set to false to remove excerpts on the homepage
